### ISSUE TITLE
Problem with restarts

### ISSUE THREAD

**Issue by pattyland** [Hereath/avea#3]
Hey there,
thanks again for putting that into PyPI!

I already got my home assistant component working with the help of your lib, but I'm having problems with restarts. As soon as I restart the docker container of home assistant, your library stops working. By "stops working" I meant than the discovery function still returns 1 bulb, but every method like "get_name()" return "None", as long as I don't reboot my host.
Could this happen because of a "config" file, like described in line 143?
Or should bluepys clear() method used before a scan?

Maybe you have an even better idea than me ;)

Greets, pattyland

**Comment by pattyland** [comment]
Hi,

no, set_brightness() does not work, but fails silently.

There is mention in the comments in line 143: https://github.com/Hereath/avea/blob/master/avea/avea.py#L143
But I already thought this was outdated, as there is no mention of a config file anywhere in the code.
I'm using the version 1.0.0 from PyPI

Of course, here is the full (and bad) code: https://pastebin.com/3QkPBB4g
At the moment it works to discover and to switch the bulb on and off. As long as it don't restart HA ;)

**Comment by pattyland** [comment]
Haha the solar flares would really explain the unexpected behavior 😄
Here I called the same script on a plain Rasbian Pi Zero 20cm away from the bulb, which just discovers bulbs, 3 times in a minute:
```
pi@hassbian:~ $ sudo -E python3 test.py
pi@hassbian:~ $ sudo -E python3 test.py
pi@hassbian:~ $ sudo -E python3 test.py
Found bulb with address 78:a5:04:7b:1a:cb !
pi@hassbian:~ $
```
I tried the static approach, which would be fine, as you have to MAC addresses for many components to configure sensors or lights for ha. Unfortunately it's not fixing my restart problem: 
```
Error while setting up platform avea
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/light/avea.py", line 39, in setup_platform
    add_devices(AveaLight(bulb))
  File "/config/custom_components/light/avea.py", line 54, in __init__
    self._brightness = round(255 * (light.get_brightness() / 100))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```
I also asked in the official ha Discord dev channel, there were the advices:

> Sounds like a hook/socket/whatever is not getting closed on Hass shutdown
> So on the restart, the resource is not available

> I don't know the details of what your component is trying to do, but yes, you should be cleaning up things that need cleaning up when Hass exits. And ideally when your component starts you may have to have some special logic to handle a bad previous exit, if you can detect such a thing

**Comment by Hereath** [comment]
I might have found the issue, which would be in fact a cleaning issue. As I rely on bluepy to properly clean up the BLE ressources, it might not be called every time, therefore being unavailable after a relaunch. I'll test the changes this afternoon, if everything goes well i'll push to git and pip afterwards. I'll update this thread accordingly.

**Comment by Hereath** [comment]
The commit related to your issue closed the issue automatically..
The changes should indeed fix the weird behaviour. Now the lib will connect and disconnect properly at each query, instead of relying on bluepy.

I'll push to pip, v1.0.2.
If it does not fix your issue, let me know !

**Comment by Hereath** [comment]
I also had this erratic behaviour of bluepy not being able to connect to the bulb when I started modifying the lib, but the latest revision is working flawlessly for me (using pure python scripts, not through HA though)..

Could you try the following script (multiple times if possible), and report any issues ? 

```python
import avea
from random import randint

for bulb in avea.discover_avea_bulbs():
  brightness = randint(10,4000)
  print("name is : "+bulb.get_name())
  bulb.set_brightness(brightness)
  print("Brightness should be",brightness,", is",bulb.get_brightness())
```

I still have some ideas for fixing this issue, we'll see how it goes.

**Comment by pattyland** [comment]
3 reboots:
```
2018-12-03 23:40:00 WARNING (SyncWorker_7) [custom_components.light.avea] name is : Fado
2018-12-03 23:40:00 WARNING (SyncWorker_7) [custom_components.light.avea] Brightness should be 2765, is 2765
```
```
2018-12-03 23:47:05 WARNING (SyncWorker_16) [custom_components.light.avea] name is : Fado
2018-12-03 23:47:05 WARNING (SyncWorker_16) [custom_components.light.avea] Brightness should be 1388, is 1388
```
```
2018-12-03 23:54:25 WARNING (SyncWorker_4) [custom_components.light.avea] name is : Fado
2018-12-03 23:54:25 WARNING (SyncWorker_4) [custom_components.light.avea] Brightness should be 1946, is 1946
```
3 restarts:
```
018-12-03 23:58:29 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform avea
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/light/avea.py", line 42, in setup_platform
    _LOGGER.warning("name is : "+bulb.get_name())
TypeError: must be str, not NoneType
```
```
2018-12-04 00:01:58 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform avea
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/light/avea.py", line 42, in setup_platform
    _LOGGER.warning("name is : "+bulb.get_name())
TypeError: must be str, not NoneType
```
```
2018-12-04 00:05:07 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform avea
Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/avea/avea.py", line 62, in connect
    self.bulb.connect(self.addr)
  File "/usr/local/lib/python3.6/site-packages/bluepy/btle.py", line 408, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.6/site-packages/bluepy/btle.py", line 402, in _connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral 78:a5:04:7b:1a:cb, addr type: public

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/light/avea.py", line 42, in setup_platform
    _LOGGER.warning("name is : "+bulb.get_name())
  File "/config/deps/lib/python3.6/site-packages/avea/avea.py", line 123, in get_name
    self.connect()
  File "/config/deps/lib/python3.6/site-packages/avea/avea.py", line 68, in connect
    raise AveaConnectError(self.addr)
avea.avea.AveaConnectError: Could not connect to 78:a5:04:7b:1a:cb
```

**Comment by Hereath** [comment]
There is something odd with your setup that I can't replicate. If you don't mind, could you explain quickly your HA config ? I would like to replicate your setup, this would be way easier to troubleshoot..

**Comment by pattyland** [comment]
Of course!
I've got a Raspberry Pi 3 with [Hass.io](https://www.home-assistant.io/hassio/), the docker based variant of [Home Assistant](https://www.home-assistant.io/).

To replicate my setup you need an [supported device](https://www.home-assistant.io/hassio/installation/) to install Hass.io, I would not recommend to use VM, as I'm not sure wether bluetooth will work fine.
Then you put [avea.py](https://pastebin.com/cp3sDVVZ) via smb or ssh in /config/config/custom_components/light/avea.py and restart Hass.io :)

**Comment by Hereath** [comment]
Thanks ! I've setup HA and copied your script, but nothing is happening. I don't even know if HA is aware of my file as nothing is showing up in the logs about it. And it looks like a hassle to setup/configure. 😭 

But in the meantime I've improved the lib a tad more. Now every object related to the Bluetooth connection (Peripheral, Delegate) are created at query time, and properly deleted afterwards. So v1.0.4 is on its way to pip. 🎉 

FWIW, during testing, I've noticed that sometimes the bulb looks completely unresponsive, exactly the same behaviour as you described. After some digging, its some low-level BLE stuff that are not properly handled. Switching the Bluetooth off then on "fixed" the problem, by running a quick 
```
bluetoothctl
> power off
[...]
> power on
[...]
> exit
```

Maybe this is a script that you could attach at an event in HA, in case the Bulb is not responding..
I'll keep testing though, let me know if the new version is any better :)

**Comment by pattyland** [comment]
Oh no, I forgot something 😥 To activate a component, no matter if integrated or custom, you have to add it to the configuration.yaml. You have to add this snipped there:
```
light:
  - platform: avea
```

Turning the Bluetooth tip on and off is good, but unfortunately the great Docker 1 click updates are always accompanied by a disadvantage; Home Assistant can't "do" such system-related things. The hypervisor must make Bluetooth available to the Docker Containers.

I will test 1.0.4 tomorrow :)

**Comment by pattyland** [comment]
Happy New Year!
I have an incredibly terrible confession to make. My first attempt to use the Avea bulb in Home Assistant was this http API in Node: https://github.com/Marmelatze/avea_server

This server was running all the time, and probably took over the connection and blocked your lib every time you restarted Home Assistant. I shut down the server and it works without any problems.

I'm incredibly sorry.

Best regards, 
Sören

**Comment by Hereath** [comment]
Hi ! Happy new year to you too ! 

This is how we learn I guess ! 😄 
The lib is more robust and resilient thanks to you, so no needs to apologise ! (Actually, I've learned a lot about BLE communications due to this issue, so thanks ! ).

I'll close the issue as it's resolved now.

Wishing you the best for 2019 !
Corentin
